"""empty message

Revision ID: 055db463dcf9
Revises: 0e115dbef341
Create Date: 2023-01-25 10:35:51.755607

"""
from alembic import op
import sqlalchemy as sa

# Second Migration!
# revision identifiers, used by Alembic.
revision = '055db463dcf9'
down_revision = '0e115dbef341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
