"""empty message

Revision ID: 843299e29e77
Revises: c01e861a58ed
Create Date: 2023-01-26 19:55:38.921457

"""
from alembic import op
import sqlalchemy as sa

# Fourth Migration
# revision identifiers, used by Alembic.
revision = '843299e29e77'
down_revision = 'c01e861a58ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    op.create_unique_constraint("email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email", "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###